// Code generated by wxbot project. DO NOT EDIT.
// Source: wxbot/engine/plugins/generate.go

package plugins

import (
	// 百度百科
	_ "wxbot/plugins/baidubaike"

	// 肯德基疯狂星期四骚话
	_ "wxbot/plugins/crazykfc"

	// 公众号消息监控转发
	_ "wxbot/plugins/ghmonitor"

	// 群组管理相关
	_ "wxbot/plugins/manager"

	// 表情包原图
	_ "wxbot/plugins/memepicture"

	// 摸鱼办
	_ "wxbot/plugins/moyuban"

	// 拼音缩写翻译
	_ "wxbot/plugins/pinyinsuoxie"

	// 漂亮妹妹
	_ "wxbot/plugins/plmm"

	// 天气查询
	_ "wxbot/plugins/weather"

	// 每日早报
	_ "wxbot/plugins/zaobao"

	// 聊天热词
	_ "wxbot/plugins/wordcloud"

	// 查wxId
	_ "wxbot/plugins/chaid"

	// 有道翻译
	_ "wxbot/plugins/youdaofanyi"

	// 自动加好友
	_ "wxbot/plugins/friendadd"

	// 选择困难症帮手
	_ "wxbot/plugins/choose"

	// 读取本地图片
	_ "wxbot/plugins/localimage"

	// 爬取图片到本地
	_ "wxbot/plugins/localimagespider"

	// news
	_ "wxbot/plugins/news"

	// 寻道大钱
	_ "wxbot/plugins/xddq"

	// 随机一句一言
	_ "wxbot/plugins/sjyjyy"

	// 随机一张头像
	_ "wxbot/plugins/sjyztx"

	// 星座运势
	_ "wxbot/plugins/xzys"

	// 情话
	_ "wxbot/plugins/love"

	// 淘宝
	_ "wxbot/plugins/tbbi"

	// acg图片
	_ "wxbot/plugins/acgimg"

	// 抢红包
	_ "wxbot/plugins/hb"

	// ChatGPT聊天，优先级必须放到最低
	_ "wxbot/plugins/chatgpt"
)
